# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ios-malrang-market' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'SwiftLint'

  # Pods for ios-malrang-market

  target 'ios-malrang-marketTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ios-malrang-marketUITests' do
    # Pods for testing
  end

end
